infrastructure/urls.py
from django.urls import path, include

from . import forms
from . import views
app_name = 'infrastructure'
urlpatterns = [
	path('', views.results, name='index' ),
	path('accounts/', include('django.contrib.auth.urls')),
	path("register", views.register, name="register"),
	path('about', views.about, name='about'),
	path('posts_guide', views.posts_guide, name='posts-guide'),
	path('comments_guide', views.comments_guide, name='comments-guide'),
	path('accounts/edit/<slug>/', views.ProfileUpdate.as_view(), name='edit-user-profile' ),
	path('accounts/<slug>/', views.ProfileDetail.as_view(), name='display-profile' ),
	path('accounts/<slug>/orgs', views.UserOrgsView, name='user-orgs-view' ),
	path('tags/<tag_name>/', views.TagUserView, name='tag-user-view'),
	path('tags/', views.TagsView, name='tags-view'),
	path('org/create', views.OrganizationCreate.as_view(), name = 'org-create'),
	path('org/<slug>', views.OrganizationDetail.as_view(), name='org-detail'),
	path('org/<slug>/edit', views.OrganizationUpdate.as_view(), name='org-edit'),
	path('publish_post/user/<slug>', views.PostCreate.as_view(), name='publish-post-user'),
	path('publish_post/org/<slug>', views.PostCreate.as_view(), name='publish-post-org'),
	path('post/<id>', views.PostView, name='post-detail'),
	path('comments/<id>', views.CommentsCreation, name='comments-creation'), #the id here is for the post that is having the comment
	path('upvote/<id>', views.PostUpView, name='upvote'),
	path('unvote/<id>', views.PostUnvoteView, name='unvote'),
	path('order_by_time', views.OrderingByTime, name='order-by-time'),
	path('order_by_votes', views.OrderingByVotes, name='order-by-votes')



]

the_social_work/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static # < this
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('infrastructure.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infrastructure/forms.py
from django.forms import CharField, ModelForm
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm

import re

def valid_hashtag(value):
	values = value.split(' ')
	for value in values:
		if not re.match(r'\B(\#[a-zA-Z]+\b)(?!;)', value) :
			raise forms.ValidationError("Name should begin with #")

class PostForm(ModelForm):
	class Meta:
		model = models.Post
		fields = [
			'content',
			'post_type',
			'is_urgent',	
		]

class OrganizationForm(ModelForm):

	class Meta:
		model= models.Organization
		fields = [
			'name',
			'slug',
			'bio',
			'avatar_thumbnail',
			'location',
			'contact_information',
		]

class TagForm(ModelForm):
	class Meta:
		model = models.Tag
		fields = ['subject_tags',]
		exclude=['name',]
	subject_tags = forms.ModelMultipleChoiceField(queryset=models.SubjectTag.objects.all())

	def __init__(self, *args, **kwargs):
		if kwargs.get('instance'):
			initial = kwargs.setdefault('initial', {})
			initial['subject_tag'] = [t.pk for t in kwargs['instance'].subject_tag_set.all()]
		return forms.ModelForm.__init__(self, *args, **kwargs)
		

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = models.Profile
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

infrastructure/views.py
from django.shortcuts import render
from .models import Profile
# Create your views here.
from django.core import exceptions
from django.http import HttpResponse, HttpResponseRedirect

import re
from . import forms
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import Profile, Tag, Organization, Post, Comment, Voters, SubjectTag
from django.views.generic.detail import DetailView
from django.urls import reverse
from .forms import PostForm, TagForm
from django.db.models import Q

from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib import messages

from infrastructure import forms
from django.db.models import Q

def results(request):

	needer = 'n'
	highest= 'h'
	needer_or_helper = request.GET.get('needer_or_helper', needer)
	highest_or_recent = request.GET.get('highest_or_recent', highest)

	if (needer_or_helper == needer):
		if (highest_or_recent == highest):
			urgent_posts = Post.objects.filter(post_type=needer_or_helper, is_urgent = True).order_by('-votes')
			nonurgent_posts = Post.objects.filter(post_type=needer_or_helper, is_urgent = False).order_by('-votes')
		else:
			urgent_posts = Post.objects.filter(post_type=needer_or_helper, is_urgent = True).order_by('-created_at')
			nonurgent_posts = Post.objects.filter(post_type=needer_or_helper, is_urgent = False).order_by('-created_at')
	else:
		if (highest_or_recent == highest):
			urgent_posts = None
			nonurgent_posts = Post.objects.filter(post_type=needer_or_helper).order_by('-votes')

		else:
			urgent_posts= None
			nonurgent_posts = Post.objects.filter(post_type=needer_or_helper).order_by('-created_at')

	ids = []
	if request.user.is_authenticated:
		#Getting the ids of all the posts the current user has upvoted
		voted_users = Voters.objects.filter(voter = request.user)
		for vote in voted_users:
			#sending the ids of the upvoted posts to template to choose when to render upvote
			#and when to render unvote
			ids.append(vote.post.id)
	
	return render(request, 'index.html', {'ids': ids, 'urgent_posts': urgent_posts, 'nonurgent_posts': nonurgent_posts, 'needer_or_helper': needer_or_helper, 'highest_or_recent': highest_or_recent})

def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("infrastructure:index")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="register.html", context={"register_form":form})

def about(request):
	return render(request, 'about.html')

def comments_guide(request):
	return render(request, 'comments_guide.html')

def posts_guide(request):
	return render(request, 'posts_guide.html')

def OrderingByTime(request):
	slug = None
	ids = []
	if request.user.is_authenticated:
		slug = request.user.slug
		voted_users = Voters.objects.filter(voter = request.user)
		for vote in voted_users:
			ids.append(vote.post.id)
	user_posts = Post.objects.all().exclude(publisher_user__isnull = True).order_by("-created_at")
	org_posts = Post.objects.all().exclude(publisher_org__isnull=True).order_by("-created_at")
	return render(request, 'index.html', {'ids' : ids,'slug' : slug, 'user_posts': user_posts, 'org_posts': org_posts})

def OrderingByVotes(request):
	slug =None
	ids=[]
	if request.user.is_authenticated:
		slug = request.user.slug
		voted_users = Voters.objects.filter(voter = request.user)
		for vote in voted_users:
			ids.append(vote.post.id)
	user_posts = Post.objects.all().exclude(publisher_user__isnull = True).order_by('-votes')
	org_posts = Post.objects.all().exclude(publisher_org__isnull=True).order_by('-votes')
	return render(request, 'index.html', {'ids' : ids,'slug' : slug, 'user_posts': user_posts, 'org_posts': org_posts})

def append_tags_to(user_or_org, POST):
	choice_tags = POST.getlist('tags2')
	tags = set()
	for tag in choice_tags:
		tag_obj = Tag.objects.get(name = tag)
		tags.add(tag_obj)

	text_input_tags = POST.getlist('tags1')[0]
	text_input_tags = text_input_tags.strip()
	text_inputs_tags = text_input_tags.split(' ')
	for tag in text_inputs_tags:
		if tag != '':
			if not tag.startswith('#') :
				tag = '#' + tag
			tag_obj, created = Tag.objects.get_or_create(name = tag)
			if created :
				tag_obj.verified = False	
			tag_obj.save()
			tags.add(tag_obj)
	user_or_org.tags.set(tags)

class ProfileUpdate(UpdateView):
	model = Profile
	fields= [
		'username',
		'bio',
		'avatar_thumbnail',
		'location',
		'contact_information'
		]

	def get_object(self):
		obj = Profile.objects.get(slug = self.kwargs.get('slug'))
		if obj != self.request.user:
			raise exceptions.PermissionDenied()
		return obj

	def get_success_url(self):
		user = self.get_object()
		POST = self.request.POST.copy()

		append_tags_to(user, POST)

		return super().get_success_url()


	def get_context_data(self, **kwargs):
		context = super(ProfileUpdate, self).get_context_data(**kwargs)
		subject_tags = SubjectTag.objects.all()
		context['subject_tags'] =  subject_tags
		context['user'] = self.get_object()
		return context 
	
	def get_queryset(self):
		base_qs = super(ProfileUpdate, self).get_queryset()
		return base_qs.filter(username=self.request.user.username)
	
	def post(self, request, *args, **kwargs):
		print(request.FILES)
		return super().post(request, *args, **kwargs)

class OrganizationUpdate(UpdateView):
	model = Organization
	form_class = forms.OrganizationForm

	def get_object(self):
		obj = Organization.objects.get(slug = self.kwargs.get('slug'))
		if self.request.user not in obj.moderators.all() :
			raise exceptions.PermissionDenied()
		return obj

	def get_success_url(self):

		org = self.get_object()
		POST = self.request.POST.copy()

		append_tags_to(org, POST)

		return super().get_success_url()

	def get_context_data(self, **kwargs):
		context = {}
		subject_tags = SubjectTag.objects.all()
		context['subject_tags'] =  subject_tags
		context['org'] = self.get_object()
		context.update(kwargs)
		return super().get_context_data(**context)

from django.views.generic.edit import FormView

class ProfileDetail(DetailView, FormView):
	model = Profile
	form_class = PostForm

	def get_object(self):
		return Profile.objects.get(slug = self.kwargs.get('slug'))

	def get_context_data(self, **kwargs):
		context = super(ProfileDetail, self).get_context_data(**kwargs)
		request = self.request
		ids=[]
		if request.user.is_authenticated:
			voted_users = Voters.objects.filter(voter = request.user)
			for vote in voted_users:
				ids.append(vote.post.id)
		context['ids'] = ids

		return context

def TagUserView(request, tag_name):
	users = Tag.objects.get(name=tag_name).profile_set
	orgs = Tag.objects.get(name=tag_name).organization_set
	return render(request, 'tag_user.html', { 'users' : users, 'orgs' : orgs})

def TagsView(request):
	tags = Tag.objects.filter(verified=True).all()
	return render(request, 'tags.html', {'tags': tags})


class OrganizationCreate(CreateView):
	model = Organization
	fields = [
		'name',
		'bio',
		'avatar_thumbnail',
		'location',
		'contact_information',
	]

	def form_valid(self, form):
		form.instance.save()
		my_p = Profile.objects.get(username=self.request.user.username)
		form.instance.moderators.add(my_p)

		org = form.instance
		POST = self.request.POST.copy()

		append_tags_to(org, POST)

		return super().form_valid(form)

	def get_context_data(self, **kwargs):
		context = {}
		subject_tags = SubjectTag.objects.all()
		context['subject_tags'] =  subject_tags
		context.update(kwargs)
		return super().get_context_data(**context)


class OrganizationDetail(DetailView):
	model = Organization

	def get_context_data(self, **kwargs) :
		context = super().get_context_data(**kwargs)
		context['form'] = PostForm
		return context

def UserOrgsView(request, slug):
	orgs = Profile.objects.get(slug=slug).organization_set
	return render(request, 'user_orgs.html', { 'orgs' : orgs})


class PostCreate(CreateView):
	from .forms import PostForm
	model = Post
	form_class = PostForm
	template_name ='profile_detail.html'

	def form_valid(self, form):
		post = form.instance
		path = self.request.get_full_path()
		if 'publish_post/user/' in path :
			post.publisher_user= self.request.user
			post.save()
		else :
			slug = self.kwargs.get('slug', None)
			publisher_org = Organization.objects.get(slug = slug)
			post.publisher_org= publisher_org
		return super().form_valid(form)

def PostView(request, id):
	post = Post.objects.get(id=id)
	if post.publisher_user :
		user = post.publisher_user
		org = None
	elif post.publisher_org :
		org = post.publisher_org
		user = None
	comments = Comment.objects.filter(post=post)
	votes = post.get_votes()
	ids = []

	if request.user.is_authenticated:
		voted_users = Voters.objects.filter(voter = request.user)
		for vote in voted_users:
			ids.append(vote.post.id)
	return render(request, 'post_detail.html', {'post': post, 'comments': comments, 'votes': votes, 'ids': ids, 'user': user, 'org':org})

def CommentsCreation(request, id):
	post = Post.objects.get(id = id)
	Comment.objects.create(content = request.POST.get('comment'), publisher_user=request.user, post = post)
	return HttpResponseRedirect(reverse('infrastructure:post-detail', args=(post.id,)))

def PostUpView(request, id):
	post = Post.objects.get(id = id)
	users = Voters.objects.filter(post = post)
	if not users:
		Voters.objects.create(post = post, voter = request.user)

	empty_list = []

	for user in users:
		empty_list.append(user.voter.slug)
	if request.user.slug not in empty_list:

		post.up_vote()
		Voters.objects.create(post = post, voter = request.user)
		post.save()
	else:
		pass
	previous_url = request.META.get('HTTP_REFERER')

	return HttpResponseRedirect(previous_url)

def PostUnvoteView(request, id):

infrastructure/templates/infrastructure/organization_detail.html
{%extends 'base.html'%}
{%block content%}

<img src="{{ object.avatar_thumbnail.url }}" >

{% if request.user in object.moderators.all %}
<h3><a href="{% url 'infrastructure:org-edit' slug=object.slug %}">Edit</a></h3>
{%endif%}

<h1>Name : {{ object.name }}</h1>
<p>Bio : {{ object.bio }}</p>
<p>Location : {{ object.location }}</p>
<p>Contact Information : {{ object.contact_information }}</p>
<p>Verification Status : 

	{% if object.verified %}
		verified ✅

	{%else%}
		not verified ❌
	{%endif%}
	
</p>
<h4>Tags</h4>
{%for tag in object.tags.all%}
<p> <a href="{% url 'infrastructure:tag-user-view' tag_name=tag.name %}">{{tag}}</a> </p>
{%endfor%}

<hr>
<h1>Submit a post</h1>
{%if request.user in object.moderators.all %}
	<form id='form1' method="post" action="{% url 'infrastructure:publish-post-org' slug=object.slug %}">
	{% csrf_token %}
	<p>{{form.content.label}}: {{form.content}}</p>
	<p>You can specify the type of your post from the dropdown menu below.</p>
	<p>You should select "needer" if your post contains a call/need for help from others.</p>
	<p>You should select "helper" if your post contains an offer of help to others.</p>
	<p>{{form.post_type.label}}: {{form.post_type}}</p>
	<p>Please specify if your call for help is urgent (ideally you need it resolved in the next few hours)!</p>
	<p>{{form.is_urgent.label}}: {{form.is_urgent}}</p>
	<input type="submit" name="submit">
	</form>
{%endif%}
<hr>
<h1>Posts</h1>
{%for post in object.org_post.all%}
<h4><a href="{%url 'infrastructure:post-detail' id=post.id%}">{{post.content}}</a></h4>
<hr>
{%endfor%}
{%endblock%}

infrastructure/templates/infrastructure/organization_form.html
{%extends 'base.html'%}
{%block content%}

<form method='POST' enctype="multipart/form-data">
	{%csrf_token%}
	{{form.as_p}}
	<p>
		You can either choose the tags you want to associate with your profile<br>
		form the "Multiple Choice Tags" section (hold Crtl for multiple selection),<br>
		or write them manually in the form of #tag in the "Written Tags" section <br>
		and seperate between them with spaces or both!
	</p>
	<label for="tags" >Written Tags</label>
	

	<input value="{% if org %}{% for tag in form.instance.tags.all %}{% if tag.verified == False%}{{tag.name}} {%endif%}{%endfor%}{%endif%}" type="text" name="tags1" id="tags" placeholder="Add a tag like #Backend_dev and separete tags with a space">
	<br><br>
	<label for="tagss">Multiple Choice Tags</label>
    <select name="tags2" multiple id="tagss" >
		{% for subject_tag in subject_tags %}
		  <optgroup label="{{subject_tag.name}}">
			{% for tag in subject_tag.tags.all %}
			<option 
				{% if tag in form.instance.tags.all %}
					selected
				{%endif%}
			>{{tag.name}}</option>
			{% endfor %}
		  </optgroup>
		{%endfor%}
	</select>
	<br><br>
	<input type="submit" name="Submit">
	
</form>
{%endblock%}

infrastructure/templates/infrastructure/profile_detail.html
{%extends 'base.html'%}

{%block content%}
<img src="{{ object.avatar_thumbnail.url }}" >
<h1>Username : {{ object.username }}</h1>
<p>Bio : {{ object.bio }}</p>
<p>Location : {{ object.location }}</p>
<p>Contact Information : {{ object.contact_information }}</p>
<p>Verification Status : 

	{% if object.verified %}
		verified ✅

	{%else%}
		not verified ❌
	{%endif%}
	
</p>
<h4>Tags</h4>
{%for tag in object.tags.all%}
<p> <a href="{% url 'infrastructure:tag-user-view' tag_name=tag.name %}">{{tag}}</a>{{tag_form.subject_tags}} </p>
{%endfor%}
<hr>
<h1>Submit a post</h1>
{% if request.user == object %}
<form id='form1' method="post" action="{% url 'infrastructure:publish-post-user' slug=request.user.slug %}">
{% csrf_token %}
	<p>{{form.content.label}}: {{form.content}}</p>
	<p>You can specify the type of your post from the dropdown menu below.</p>
	<p>You should select "needer" if your post contains a call/need for help from others.</p>
	<p>You should select "helper" if your post contains an offer of help to others.</p>
	<p>{{form.post_type.label}}: {{form.post_type}}</p>
	<p>Please specify if your call for help is urgent (ideally you need it resolved in the next few hours)!</p>
	<p>{{form.is_urgent.label}}: {{form.is_urgent}}</p>
	<input type="submit" name="submit">
</form>
{%endif%}
<hr>
<h1>Posts</h1>
{%for post in object.user_post.all%}
<h4><a href="{%url 'infrastructure:post-detail' id=post.id%}">{{post.content}}</a></h4>

	{%if request.user.is_authenticated%}
		{%if post.id not in ids%}

				<a href="{%url 'infrastructure:upvote' id=post.id%}">Up vote ({{post.get_votes}})</a>
		{%else%}


				<a href="{%url 'infrastructure:unvote' id=post.id%}">Unvote ({{post.get_votes}})</a>

		{%endif%}
	{%endif%}

<hr>


{%endfor%}



{%endblock%}

infrastructure/templates/infrastructure/profile_form.html
{%extends 'base.html'%}
{%block content%}
<style>
body  {
  text-align: center;
  vertical-align: middle;
 }
p * { 
	vertical-align: middle; 
	font-size : 20px ;
}​ 
</style>
<form method="post" enctype="multipart/form-data">
	<h3>Your Picture</h3>
	<img src="{{ form.instance.avatar_thumbnail.url }}" />
	{% csrf_token %}
	
    {%for item in form%}
    <p>
    	{%if  item.label != 'Tags'%}
    	{{item.label}} 
    	{{item}} 
    	<p>
    		{%if item.label == 'Username'%}
    			*Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    		{%endif%}
    	</p>
    	{%else%}
    		{{item.label}} {{item}} 
    		
    	{%endif%}

    </p>
    {%endfor%}
	<p>
		You can either choose the tags you want to associate with your profile<br>
		form the "Multiple Choice Tags" section (hold Crtl for multiple selection),<br>
		or write them manually in the form of #tag in the "Written Tags" section <br>
		and seperate between them with spaces or both!
	</p>
	<label for="tags" >Written Tags</label>
	<input value="{% for tag in form.instance.tags.all %}{% if not tag.verified %} {{tag.name}}{%endif%}{%endfor%}" type="text" name="tags1" id="tags" placeholder="Add a tag like #Backend_dev and separete tags with a space">
	<br><br>
	<label for="tagss">Multiple Choice Tags</label>
    <select name="tags2" multiple id="tagss" >
		{% for subject_tag in subject_tags %}
		  <optgroup label="{{subject_tag.name}}">
			{% for tag in subject_tag.tags.all %}
			<option 
				{% if tag in form.instance.tags.all %}
					selected
				{%endif%}
			>{{tag.name}}</option>
			{% endfor %}
		  </optgroup>
		{%endfor%}
	</select>
	<br><br>

    <input type="submit" value="Update">
</form>
{%endblock%}