infrastructure/urls.py
from django.urls import path, include

from . import forms
from . import views
app_name = 'infrastructure'
urlpatterns = [
	path('', views.results, name='index' ),
	path('accounts/', include('django.contrib.auth.urls')),
	path("register", views.register, name="register"),
	path('about', views.about, name='about'),
	path('posts_guide', views.posts_guide, name='posts-guide'),
	path('comments_guide', views.comments_guide, name='comments-guide'),
	path('accounts/edit/<slug>/', views.ProfileUpdate.as_view(), name='edit-user-profile' ),
	path('accounts/<slug>/', views.ProfileDetail.as_view(), name='display-profile' ),
	path('accounts/<slug>/orgs', views.UserOrgsView, name='user-orgs-view' ),
	path('tags/<tag_name>/', views.TagUserView, name='tag-user-view'),
	path('tags/', views.TagsView, name='tags-view'),
	path('org/create', views.OrganizationCreate.as_view(), name = 'org-create'),
	path('org/<slug>', views.OrganizationDetail.as_view(), name='org-detail'),
	path('org/<slug>/edit', views.OrganizationUpdate.as_view(), name='org-edit'),
	path('publish_post/user/<slug>', views.PostCreate.as_view(), name='publish-post-user'),
	path('publish_post/org/<slug>', views.PostCreate.as_view(), name='publish-post-org'),
	path('post/<id>', views.PostView, name='post-detail'),
	path('comments/<id>', views.CommentsCreation, name='comments-creation'), #the id here is for the post that is having the comment
	path('upvote/<id>', views.PostUpView, name='upvote'),
	path('unvote/<id>', views.PostUnvoteView, name='unvote'),
	path('order_by_time', views.OrderingByTime, name='order-by-time'),
	path('order_by_votes', views.OrderingByVotes, name='order-by-votes')



]

the_social_work/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static # < this
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('infrastructure.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infrastructure/forms.py
from django.forms import CharField, ModelForm
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm

import re

def valid_hashtag(value):
	values = value.split(' ')
	for value in values:
		if not re.match(r'\B(\#[a-zA-Z]+\b)(?!;)', value) :
			raise forms.ValidationError("Name should begin with #")

class PostForm(ModelForm):
	class Meta:
		model = models.Post
		fields = [
			'content',
			'post_type',
			'is_urgent',	
		]

class OrganizationForm(ModelForm):

	class Meta:
		model= models.Organization
		fields = [
			'name',
			'slug',
			'bio',
			'avatar_thumbnail',
			'location',
			'contact_information',
		]

class TagForm(ModelForm):
	class Meta:
		model = models.Tag
		fields = ['subject_tags',]
		exclude=['name',]
	subject_tags = forms.ModelMultipleChoiceField(queryset=models.SubjectTag.objects.all())

	def __init__(self, *args, **kwargs):
		if kwargs.get('instance'):
			initial = kwargs.setdefault('initial', {})
			initial['subject_tag'] = [t.pk for t in kwargs['instance'].subject_tag_set.all()]
		return forms.ModelForm.__init__(self, *args, **kwargs)
		

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = models.Profile
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

infrastructure/views.py
from django.shortcuts import render
from .models import Profile
# Create your views here.
from django.core import exceptions
from django.http import HttpResponse, HttpResponseRedirect

import re
from . import forms
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import Profile, Tag, Organization, Post, Comment, Voters, SubjectTag
from django.views.generic.detail import DetailView
from django.urls import reverse
from .forms import PostForm, TagForm
from django.db.models import Q

from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib import messages

from infrastructure import forms
from django.db.models import Q

def results(request):

	needer = 'n'
	highest= 'h'
	needer_or_helper = request.GET.get('needer_or_helper', needer)
	highest_or_recent = request.GET.get('highest_or_recent', highest)

	if (needer_or_helper == needer):
		if (highest_or_recent == highest):
			urgent_posts = Post.objects.filter(post_type=needer_or_helper, is_urgent = True).order_by('-votes')
			nonurgent_posts = Post.objects.filter(post_type=needer_or_helper, is_urgent = False).order_by('-votes')
		else:
			urgent_posts = Post.objects.filter(post_type=needer_or_helper, is_urgent = True).order_by('-created_at')
			nonurgent_posts = Post.objects.filter(post_type=needer_or_helper, is_urgent = False).order_by('-created_at')
	else:
		if (highest_or_recent == highest):
			urgent_posts = None
			nonurgent_posts = Post.objects.filter(post_type=needer_or_helper).order_by('-votes')

		else:
			urgent_posts= None
			nonurgent_posts = Post.objects.filter(post_type=needer_or_helper).order_by('-created_at')

	ids = []
	if request.user.is_authenticated:
		#Getting the ids of all the posts the current user has upvoted
		voted_users = Voters.objects.filter(voter = request.user)
		for vote in voted_users:
			#sending the ids of the upvoted posts to template to choose when to render upvote
			#and when to render unvote
			ids.append(vote.post.id)
	
	return render(request, 'index.html', {'ids': ids, 'urgent_posts': urgent_posts, 'nonurgent_posts': nonurgent_posts, 'needer_or_helper': needer_or_helper, 'highest_or_recent': highest_or_recent})

def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("infrastructure:index")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="register.html", context={"register_form":form})

def about(request):
	return render(request, 'about.html')

def comments_guide(request):
	return render(request, 'comments_guide.html')

def posts_guide(request):
	return render(request, 'posts_guide.html')

def OrderingByTime(request):
	slug = None
	ids = []
	if request.user.is_authenticated:
		slug = request.user.slug
		voted_users = Voters.objects.filter(voter = request.user)
		for vote in voted_users:
			ids.append(vote.post.id)
	user_posts = Post.objects.all().exclude(publisher_user__isnull = True).order_by("-created_at")
	org_posts = Post.objects.all().exclude(publisher_org__isnull=True).order_by("-created_at")
	return render(request, 'index.html', {'ids' : ids,'slug' : slug, 'user_posts': user_posts, 'org_posts': org_posts})

def OrderingByVotes(request):
	slug =None
	ids=[]
	if request.user.is_authenticated:
		slug = request.user.slug
		voted_users = Voters.objects.filter(voter = request.user)
		for vote in voted_users:
			ids.append(vote.post.id)
	user_posts = Post.objects.all().exclude(publisher_user__isnull = True).order_by('-votes')
	org_posts = Post.objects.all().exclude(publisher_org__isnull=True).order_by('-votes')
	return render(request, 'index.html', {'ids' : ids,'slug' : slug, 'user_posts': user_posts, 'org_posts': org_posts})

def append_tags_to(user_or_org, POST):
	choice_tags = POST.getlist('tags2')
	tags = set()
	for tag in choice_tags:
		tag_obj = Tag.objects.get(name = tag)
		tags.add(tag_obj)

	text_input_tags = POST.getlist('tags1')[0]
	text_input_tags = text_input_tags.strip()
	text_inputs_tags = text_input_tags.split(' ')
	for tag in text_inputs_tags:
		if tag != '':
			if not tag.startswith('#') :
				tag = '#' + tag
			tag_obj, created = Tag.objects.get_or_create(name = tag)
			if created :
				tag_obj.verified = False	
			tag_obj.save()
			tags.add(tag_obj)
	user_or_org.tags.set(tags)

class ProfileUpdate(UpdateView):
	model = Profile
	fields= [
		'username',
		'bio',
		'avatar_thumbnail',
		'location',
		'contact_information'
		]

	def get_object(self):
		obj = Profile.objects.get(slug = self.kwargs.get('slug'))
		if obj != self.request.user:
			raise exceptions.PermissionDenied()
		return obj

	def get_success_url(self):
		user = self.get_object()
		POST = self.request.POST.copy()

		append_tags_to(user, POST)

		return super().get_success_url()


	def get_context_data(self, **kwargs):
		context = super(ProfileUpdate, self).get_context_data(**kwargs)
		subject_tags = SubjectTag.objects.all()
		context['subject_tags'] =  subject_tags
		context['user'] = self.get_object()
		return context 
	
	def get_queryset(self):
		base_qs = super(ProfileUpdate, self).get_queryset()
		return base_qs.filter(username=self.request.user.username)
	
	def post(self, request, *args, **kwargs):
		print(request.FILES)
		return super().post(request, *args, **kwargs)

class OrganizationUpdate(UpdateView):
	model = Organization
	form_class = forms.OrganizationForm

	def get_object(self):
		obj = Organization.objects.get(slug = self.kwargs.get('slug'))
		if self.request.user not in obj.moderators.all() :
			raise exceptions.PermissionDenied()
		return obj

	def get_success_url(self):

		org = self.get_object()
		POST = self.request.POST.copy()

		append_tags_to(org, POST)

		return super().get_success_url()

	def get_context_data(self, **kwargs):
		context = {}
		subject_tags = SubjectTag.objects.all()
		context['subject_tags'] =  subject_tags
		context['org'] = self.get_object()
		context.update(kwargs)
		return super().get_context_data(**context)

from django.views.generic.edit import FormView

class ProfileDetail(DetailView, FormView):
	model = Profile
	form_class = PostForm

	def get_object(self):
		return Profile.objects.get(slug = self.kwargs.get('slug'))

	def get_context_data(self, **kwargs):
		context = super(ProfileDetail, self).get_context_data(**kwargs)
		request = self.request
		ids=[]
		if request.user.is_authenticated:
			voted_users = Voters.objects.filter(voter = request.user)
			for vote in voted_users:
				ids.append(vote.post.id)
		context['ids'] = ids

		return context

def TagUserView(request, tag_name):
	users = Tag.objects.get(name=tag_name).profile_set
	orgs = Tag.objects.get(name=tag_name).organization_set
	return render(request, 'tag_user.html', { 'users' : users, 'orgs' : orgs})

def TagsView(request):
	tags = Tag.objects.filter(verified=True).all()
	return render(request, 'tags.html', {'tags': tags})


class OrganizationCreate(CreateView):
	model = Organization
	fields = [
		'name',
		'bio',
		'avatar_thumbnail',
		'location',
		'contact_information',
	]

	def form_valid(self, form):
		form.instance.save()
		my_p = Profile.objects.get(username=self.request.user.username)
		form.instance.moderators.add(my_p)

		org = form.instance
		POST = self.request.POST.copy()

		append_tags_to(org, POST)

		return super().form_valid(form)

	def get_context_data(self, **kwargs):
		context = {}
		subject_tags = SubjectTag.objects.all()
		context['subject_tags'] =  subject_tags
		context.update(kwargs)
		return super().get_context_data(**context)


class OrganizationDetail(DetailView):
	model = Organization

	def get_context_data(self, **kwargs) :
		context = super().get_context_data(**kwargs)
		context['form'] = PostForm
		return context

def UserOrgsView(request, slug):
	orgs = Profile.objects.get(slug=slug).organization_set
	return render(request, 'user_orgs.html', { 'orgs' : orgs})


class PostCreate(CreateView):
	from .forms import PostForm
	model = Post
	form_class = PostForm
	template_name ='profile_detail.html'

	def form_valid(self, form):
		post = form.instance
		path = self.request.get_full_path()
		if 'publish_post/user/' in path :
			post.publisher_user= self.request.user
			post.save()
		else :
			slug = self.kwargs.get('slug', None)
			publisher_org = Organization.objects.get(slug = slug)
			post.publisher_org= publisher_org
		return super().form_valid(form)

def PostView(request, id):
	post = Post.objects.get(id=id)
	if post.publisher_user :
		user = post.publisher_user
		org = None
	elif post.publisher_org :
		org = post.publisher_org
		user = None
	comments = Comment.objects.filter(post=post)
	votes = post.get_votes()
	ids = []

	if request.user.is_authenticated:
		voted_users = Voters.objects.filter(voter = request.user)
		for vote in voted_users:
			ids.append(vote.post.id)
	return render(request, 'post_detail.html', {'post': post, 'comments': comments, 'votes': votes, 'ids': ids, 'user': user, 'org':org})

def CommentsCreation(request, id):
	post = Post.objects.get(id = id)
	Comment.objects.create(content = request.POST.get('comment'), publisher_user=request.user, post = post)
	return HttpResponseRedirect(reverse('infrastructure:post-detail', args=(post.id,)))

def PostUpView(request, id):
	post = Post.objects.get(id = id)
	users = Voters.objects.filter(post = post)
	if not users:
		Voters.objects.create(post = post, voter = request.user)

	empty_list = []

	for user in users:
		empty_list.append(user.voter.slug)
	if request.user.slug not in empty_list:

		post.up_vote()
		Voters.objects.create(post = post, voter = request.user)
		post.save()
	else:
		pass
	previous_url = request.META.get('HTTP_REFERER')

	return HttpResponseRedirect(previous_url)

def PostUnvoteView(request, id):

infrastructure/templates/about.html
{%extends 'base.html'%}
{%block content%}

Helper is a community for solving problems and helping whoever needs help whatever the type of the help or the background of the person who is in need of help.
<br>
Any person and any case that needs help is welcome on Helper except the following:
It's not welcome for any content calling for anything that conflicts the right of any human to enjoy his basic rights mentioned in The Universal Declaration of Human Rights.
<br>
It's not welcome for any person or any content that discriminates between people on any basis whether it's religion, race or any other.
If you are going to put your case on Helper, you have to accept the help from any person with any background and if you are going to help
someone on Helper you need to be able to offer the help to anyone no matter what their background is.
<br>
<br>
Please consider the following points when publishing your case on Helper:
<br>
When writing the title of your case please try to mention in short the type of the problem you are facing (in case of a needer post)
 or the opportunity that you are presenting (in case of a helper post).
<br>
Try to make the title a sufficient source for the reader to know if he/she can help you or not and not force him/her to open the post to know so.
<br>
Try to mention in the content of your post all the details that the reader or possible helper might need to know to avoid the need for asking questions and 
answering them in the comments.
<br>
 Try to mention clearly in your post the type of problem you are facing and the type of help you would like to get and that is to ensure that
 you get the help that you need and avoid having posts that are ambiguious with no clear purpose behind.
<br>
When putting your case on Helper try to avoid using negative language that does nothing but help 
spread negative emotions like "This is a corrupt system", or "injustice is the new norm"
<br>
 It's forbidden to publish your case for any reason other than getting help, for example it's forbidden to publish your case to open
 the door of discussion in a specific domain or to increase awareness.

<br>
<br>

Please consider the following points when commentiong on Helper:
<br>
Please try to not write comments with content that doesn't really help the owner of the case like "That's a big problem", or "hope you solve it soon"
<br>
Posts on Helper either belong to the website (it contains a problem or a solution to one) or don't belong to the website and there is nothing in between,
so Helper doesn't cooperate with any type of negative or judgemental comments towards the owner of the post, Helper is open to everyone and to all kinds
of needers' or helpers' posts.
<br>
In the case of answering a scientific or medical question please reply with relaible sources that support your answer, that is to avoid spreading false
information and news.
<br>
Please reply with the same language the poster of the case wrote their post in.




{%endblock%}

infrastructure/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{%block title%}
		{%endblock%}
	</title>
</head>

<style>
	body {
		text-align: center;
 	 	vertical-align: middle;
	}
	p *{
		vertical-align: middle;
	}
</style>

<body>
	{% if request.user.is_authenticated %}
	<h1><a href="{% url 'infrastructure:edit-user-profile' slug=request.user.slug %}">Edit Profile</a>
	</h1>
	<h1>
		<a href="{% url 'infrastructure:display-profile' slug=request.user.slug%} ">Display Profile</a>
	</h1>
	<h1>
		<a href="{% url 'infrastructure:org-create' %}">Create Organization</a>
	</h1>
	<h1>
		<a href="{% url 'infrastructure:user-orgs-view' slug=request.user.slug%}"> Your Organizations </a>
	</h1>
	{%endif%}
	<h1>
		<a href="{% url 'infrastructure:index'%}"> Index </a>
	</h1>
	<h1>
		<a href="{% url 'infrastructure:about'%}">About</a>
	</h1>
	{%if not request.user.is_authenticated %}
	<h1>
		<a href="{% url 'infrastructure:login' %}">Log In</a>
	</h1>
	<h1>
		<a href="{% url 'infrastructure:register' %}">Register</a>
	</h1>
	{%else%}
	<h1>
		<a href="{% url 'infrastructure:logout' %}">Log Out</a>
	</h1>

	{%endif%}

<hr>
{%block content%}
{%endblock%}

</html>

infrastructure/templates/comments_guide.html
{%extends 'base.html'%}
{%block content%}
من فضلك ضع في اعتبارك النقاط التالية عند نشر تعليقك علي "مُساعد":
تجنب انواع التعليقات التي لا تحتوي علي ما قد يفيد صاحب المشكلة، مثال علي التعليقات الغير مرحب بها :  "كان الله في عونك" أو "هذه مشكلة عويصة"
في "مُساعد" المنشورات إما أن تنتمي للموقع (شخص يعرض مشكلته) أو لا تنتمي (منشور لا يعبر عن مشكلة) ولا يوجد حالة في المنتصف ، فإما أن يكون المنشور بحاجة إلى المساعدة أو يكون غير منتمي للموقع من الأساس ، ولذلك فـ"مُساعد" لا يتهاون مع أي نوع من التعليقات السلبية أو الناقدة لصاحب المشكلة أو الساخرة من المشكلة، مجتمع "مُساعد" مفتوح للجميع و لكل المشاكل مهما كان نوعها.
في حالة الرد على سؤال علمي أو طبي أو وضع محتوي علمي أو طبي يجب وضع مصدر موثوق فيه منعا للشائعات و انتشار الأفكار المغلوطة.
"مُساعد" ليس مساحة اعلانية مفتوحة لذلك، في حال الرغبة في وضع إعلان برجاء التواصل مع إدارة الموقع.
برجاء التعليق بلغة من يطلب المساعدة قدر الإمكان، مثلا الابتعاد عن الإنجليزية إن كان الطلب بالعربية، والابتعاد عن استخدام ال franko قدر الإمكان.
في حالة استخدام روابط خارجيه يفضل الاستعانة بموقع shorten لتبسيط قرأت التعليق في حالة وجود أكثر من رابط.
{%endblock%}

infrastructure/templates/index.html
{%extends 'base.html'%}

{%block content%}

<form method="get">
<div>Select the type of posts to show :</div>
<div>The "needer" will show posts of needers or people who need help.</div>
<div>the "helper" will show posts of helpers or people who offer help.</div>
<select name="needer_or_helper" id = 'type_post'>
	<option value="n"
		{% if needer_or_helper == 'n'%}
			selected
		{%endif%}
	> needer </option>
	<option value="h"
		{% if needer_or_helper == 'h'%}
			selected
		{%endif%}
	> helper </option>
</select>
and
<select name="highest_or_recent">
	<option value="h"
		{% if highest_or_recent == 'h'%}
			selected
		{%endif%}
	> Highest Votes </option>
	<option value="r"
		{% if highest_or_recent == 'r'%}
			selected
		{%endif%}
	> Most Recent </option>
</select>
<input type="submit" value="Apply">
</form>
<br>
<h1>.:Posts:.</h1>
<br>
{% if urgent_posts %}
<h2>Urgent Posts</h2>
	{% for post in urgent_posts %}
		{%if request.user.is_authenticated%}
			{%if post.id not in ids%}
					<a href="{%url 'infrastructure:upvote' id=post.id%}">Up vote ({{post.get_votes}})</a>
			{%else%}
					<a href="{%url 'infrastructure:unvote' id=post.id%}">Unvote ({{post.get_votes}})</a>
			{%endif%}
		{%endif%}
		"<a href="{%url 'infrastructure:post-detail' id=post.id%}">{{post.content}}</a>" 
		by 
		{% if post.publisher_user.slug %}
			<a href="{%url 'infrastructure:display-profile' slug=post.publisher_user.slug%}">{{post.publisher_user.slug}}</a>
		{%else%}
			<a href="{%url 'infrastructure:org-detail' slug=post.publisher_org.slug%}">{{post.publisher_org.name}}</a>
		{%endif%}
		<br>
		<br>
	{%endfor%}
{%endif%}
<br>
<br>
<h2>Non-urgent Posts</h2>
{%for post in nonurgent_posts%}
	{%if request.user.is_authenticated%}
		{%if post.id not in ids%}
				<a href="{%url 'infrastructure:upvote' id=post.id%}">Up vote ({{post.get_votes}})</a>
		{%else%}
				<a href="{%url 'infrastructure:unvote' id=post.id%}">Unvote ({{post.get_votes}})</a>
		{%endif%}
	{%endif%}
	"<a href="{%url 'infrastructure:post-detail' id=post.id%}">{{post.content}}</a>"
	by
	{% if post.publisher_user.slug %}
		<a href="{%url 'infrastructure:display-profile' slug=post.publisher_user.slug%}">{{post.publisher_user.slug}}</a>
	{%else%}
		<a href="{%url 'infrastructure:org-detail' slug=post.publisher_org.slug%}">{{post.publisher_org.name}}</a>
	{%endif%}
	<br>
	<br>
{%endfor%}
<!--
<h1>
<a href="{%url 'infrastructure:order-by-time'%}">Recent posts</a> ||
<a href="{%url 'infrastructure:order-by-votes'%}">Highest votes</a>
</h1>
<h1>Posts from users</h1>
<h3>
	{%for post in user_posts%}
		{%if request.user.is_authenticated%}

	
		{%if post.id not in ids%}
				<a href="{%url 'infrastructure:upvote' id=post.id%}">Up vote ({{post.get_votes}})</a>
		{%else%}
				<a href="{%url 'infrastructure:unvote' id=post.id%}">Unvote ({{post.get_votes}})</a>

		{%endif%}
		{%endif%}
"<a href="{%url 'infrastructure:post-detail' id=post.id%}">{{post.content}}</a>" 
	by 
	<a href="{%url 'infrastructure:display-profile' slug=post.publisher_user.slug%}">{{post.publisher_user.slug}}</a>
	<br>
	<br>
{%endfor%}
</h3>
<h1>Posts from Organizations</h1>
<h3>
	{%for post in org_posts%}
		{%if request.user.is_authenticated%}
		{%if post.id not in ids%}
				<a href="{%url 'infrastructure:upvote' id=post.id%}">Up vote ({{post.get_votes}})</a>
		{%else%}
				<a href="{%url 'infrastructure:unvote' id=post.id%}">Unvote ({{post.get_votes}})</a>

		{%endif%}
		{%endif%}
	"<a href="{%url 'infrastructure:post-detail' id=post.id%}">{{post.content}}"</a>
		 by 
		<a href="{%url 'infrastructure:org-detail' slug=post.publisher_org.slug%}">{{post.publisher_org.name}}</a>
		<br>
		<br>
	{%endfor%}
</h3>
-->
{%endblock%}

infrastructure/templates/post_detail.html
{%extends 'base.html'%}
{%block content%}
	{%if request.user.is_authenticated%}
		{%if post.id not in ids%}

				<a href="{%url 'infrastructure:upvote' id=post.id%}">Up vote ({{post.get_votes}})</a>
		{%else%}


				<a href="{%url 'infrastructure:unvote' id=post.id%}">Unvote ({{post.get_votes}})</a>

		{%endif%}
	{%endif%}
{% if user %}
<h6>By : <a href="{% url 'infrastructure:display-profile' slug=user.slug%}">{{user.slug}}</a></h6>
<img src="{{ user.avatar_thumbnail.url }}" >

{%elif org%}
<h6>By : <a href="{% url 'infrastructure:org-detail' slug=org.slug%}">{{org.slug}}</a></h6>
<img src="{{ org.avatar_thumbnail.url }}" >

{%endif%}
<h3>{{post.content}}</h3>
<hr>
<h2>Comments</h2>
{%for comment in comments%}
<h2>"{{comment.content}}" by {{comment.publisher_user}} <img src="{{ comment.publisher_user.avatar_thumbnail.url }}" >
 </h2>
{%endfor%}
{%if request.user.is_authenticated%}
<h1>Submit a comment</h1>
<form method='post' action="{%url 'infrastructure:comments-creation' id=post.id%}">
	{% csrf_token %}

	<input type="text" name="comment">
	<input type="submit" name="submit comment">
</form>
{%endif%}
{%endblock%}

infrastructure/templates/posts_guide.html
{%extends 'base.html'%}
{%block content%}
من فضلك ضع في اعتبارك النقاط التالية عند نشر مشكلتك علي "مساعد" 
عند كتابة عنوان المنشور حاول أن تذكر بإيجاز نوع المشكلة 
حاول أن تجعل العنوان مصدر كافي للقارئ ليعلم من خلاله إذا كان سيستطيع مساعدتك ام لا و عدم تكبيد القارئ عناء فتح المنشور لمعرفة ذلك
حاول أن تذكر في محتوي منشورك كل التفاصيل التي قد تهم القارئ او المساعد المحتمل بحيث نتجنب عناء طرح الاسئلة و الإجابة عليها في التعليقات
حاول ان تذكر في محتوي منشورك بشكل واضح و صريح نوع المشكلة التي تواجهها و شكل المساعدة الذي تود الحصول عليه ، و ذلك لضمان حصولك علي شكل المساعدة المناسب لمشكلتك و تجنب نوع المنشورات الغير واضح المراد أو المغزي منها
عند ذكر مشكلتك علي "مساعد" حاول تجنب استخدام الكلمات او الجمل ذات الطابع السلبي و التي لن تفيد القارئ في شئ سوي نشر المشاعر السلبية ، مثال "الظلم أصبح فاحش" أو "هذه بلد خربانة"
يمنع منعا باتًا نشر مشكلتك علي "مساعد" إذا لم يكن الهدف من وراء نشرها إيجاد المساعدة ، فمثلا ممنوع نشر مشكلة للفت نظر الرأي العام او فتح باب المناقشة في موضوع ما .



{%endblock%}

infrastructure/templates/register.html
{% extends "base.html" %}

{% block content %} 

<!--Register--> 
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form }}                    
		<button type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'infrastructure:login'%}">login</a> instead.</p>
</div>

{% endblock %}

infrastructure/templates/tag_user.html
{%extends 'index.html'%}
{%block content%}
<h1>Users</h1>
{%for user in users.all%}
<h1><a href="{% url 'infrastructure:display-profile' slug=user.slug %}">{{user.username}}</a></h1>
{%endfor%}

<h1>Organizations</h1>
{%for org in orgs.all%}
<h1><a href="{% url 'infrastructure:org-detail' slug=org.slug %}">{{org.name}}</a></h1>
{%endfor%}
{%endblock%}

infrastructure/templates/tags.html
{%extends 'base.html'%}
{%block content%}
{%for tag in tags%}
	<h1><a href="{% url 'infrastructure:tag-user-view' tag_name=tag.name%}">{{tag}}</h1>
{%endfor%}
{%endblock%}

infrastructure/templates/user_orgs.html
{%extends 'base.html'%}
{%block content%}

{%for org in orgs.all%}
<h1>
<a href="{% url 'infrastructure:org-detail' slug=org.slug %}">{{org.name}}</a>
</h1>
{%endfor%}
{%endblock%}